spring.application.name=eduhub-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/eduhub
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8089
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Session configuration
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.path=/
server.servlet.session.timeout=30m
server.servlet.session.tracking-modes=cookie

zoom.api.client-id=8YDG3EW2S0aVSE9PrveiNQ
zoom.api.client-secret=bsnMyzZtPK8F3L4FM77y48UHNhQ2AstS
zoom.redirect.uri=http://localhost:8089/api/auth/zoom/callback
cloudinary.cloud_name=dpwgloymm
cloudinary.api_key=517847241762175


cloudinary.api_secret=45YirWisWWzmv3kBkR425NBQ3EI